path.page.login = /login.jsp
path.page.main = /home/main.jsp
path.page.home.admin = /home/admin/admin.jsp
path.page.home.admin.users = admin/resources/users.jsp
path.page.home.sysadmin.devices = sysadmin/resources/alldevices.jsp
path.page.home.sysadmin.queries = sysadmin/resources/queries.jsp
path.page.home.moderator = /home/moderator/moderator.jsp
path.page.home.officeemployee = /home/officeemployee/officeemployee.jsp
path.page.home.nulluser = /home/nulluser.jsp

path.page.header.admin = /home/admin/resources/header.jsp
path.page.header.sysadmin = /home/sysadmin/resources/header.jsp
path.page.header.moderator = /home/moderator/resources/header.jsp
path.page.header.officeemployee = /home/officeemployee/resources/header.jsp

path.page.home.moderator.users = moderator/resources/users.jsp
path.page.home.moderator.queries = moderator/resources/queries.jsp

path.page.home.officeemployee.devices = officeemployee/resources/devices.jsp
path.page.home.officeemployee.userdevices = officeemployee/resources/userdevices.jsp
path.page.home.officeemployee.userqueries = officeemployee/resources/userqueries.jsp

path.page.index = /index.jsp 

path.page.error.sessionended = /error/sessionended.jsp
path.page.error.accessdenied = /error/accessdenied.jsp
path.page.error.blocked = /error/blockeduser.jsp
path.page.error.nullpage = /error/notfoundpage.jsp

oracle.userrole.id.admin = 1
oracle.userrole.id.moderator = 2
oracle.userrole.id.officeemployee = 3

oracle.userrole.name = role_name
oracle.userrole.roleid = role_id

oracle.userdata.id = user_id
oracle.userdata.login = login
oracle.userdata.password = password_hash
oracle.userdata.isblocked = is_blocked
oracle.userdata.isauthorized = is_authorized
oracle.userdata.name = user_name
oracle.userdata.roleid = role_id
oracle.userdata.dateregistration = date_registration

oracle.officedevice.id = device_id
oracle.officedevice.name = device_name
oracle.officedevice.timereceiving = time_receiving
oracle.officedevice.timeremoving = time_removing
oracle.officedevice.userid = user_id

oracle.querystatus.status = status_name
oracle.querystatus.id = status_id

oracle.querytype.id = type_id
oracle.querytype.name = type_name

oracle.query.id = query_id
oracle.query.userid = user_id
oracle.query.deviceid = device_id
oracle.query.timesending = time_sending
oracle.query.timeclosing = time_closing
oracle.query.querytype = query_type
oracle.query.status = status
oracle.query.usermessage = user_message
oracle.query.response = response

query.oracle.userdata.getuser = SELECT * FROM UserData JOIN UserRole ON UserData.role_id = UserRole.role_id WHERE login = ? AND password_hash = ?
query.oracle.userdata.getusers = SELECT * FROM UserData JOIN UserRole ON UserData.role_id = UserRole.role_id
query.oracle.userdata.insert = INSERT INTO UserData (login, password_hash, user_name, role_id, date_registration) VALUES (?, ?, ?, ?, SYSDATE)
query.oracle.userdata.isexist = SELECT COUNT(*) FROM UserData WHERE login = ?
query.oracle.userdata.delete = DELETE FROM UserData WHERE user_id = ?
query.oracle.userdata.setonline = UPDATE UserData SET is_authorized = 1 WHERE user_id = ?
query.oracle.userdata.isblocked = SELECT is_blocked FROM UserData WHERE user_id = ?
query.oracle.userdata.setoffline = UPDATE UserData SET is_authorized = 0 WHERE user_id = ?
query.oracle.userdata.edituserdata = UPDATE UserData SET role_id = ?, user_name = ? WHERE user_id = ?
query.oracle.userdata.getuserrole = SELECT role_id FROM UserData WHERE user_id = ?
query.oracle.userdata.blockuser = UPDATE UserData SET is_blocked = 1 WHERE user_id = ?
query.oracle.userdata.unblockuser = UPDATE UserData SET is_blocked = 0 WHERE user_id = ?

query.oracle.officedevice.createdevice = INSERT INTO OfficeDevice (device_name, time_receiving) VALUES (?, SYSDATE)
query.oracle.officedevice.deletedevice = DELETE FROM OfficeDevice WHERE device_id = ?
query.oracle.officedevice.backdevice = UPDATE OfficeDevice SET user_id = NULL WHERE device_id = ?
query.oracle.officedevice.givedevice = UPDATE OfficeDevice SET user_id = ? WHERE device_id = ?
query.oracle.officedevice.getdeviceuser = SELECT user_id FROM OfficeDevice WHERE device_id = ?
query.oracle.officedevice.backalldevices = UPDATE OfficeDevice SET user_id = NULL WHERE user_id = ?
query.oracle.officedevice.getfreedevices = SELECT * FROM OfficeDevice WHERE user_id IS NULL
query.oracle.officedevice.getuserdevices = SELECT * FROM OfficeDevice WHERE user_id = ?
query.oracle.officedevice.getalldevices = SELECT * FROM OfficeDevice LEFT JOIN UserData ON OfficeDevice.user_id = UserData.user_id ORDER BY device_id ASC

query.oracle.query.getuserqueries = SELECT * FROM Queries JOIN QueryType ON queries.query_type = querytype.type_id JOIN querystatus ON queries.status = querystatus.status_id JOIN UserData ON queries.user_id = UserData.user_id JOIN OfficeDevice ON queries.device_id = OfficeDevice.device_id WHERE queries.user_id = ? ORDER BY query_id
query.oracle.query.getallqueries = SELECT * FROM Queries JOIN QueryType ON queries.query_type = querytype.type_id JOIN querystatus ON queries.status = querystatus.status_id JOIN UserData ON queries.user_id = UserData.user_id JOIN OfficeDevice ON queries.device_id = OfficeDevice.device_id ORDER BY query_id
query.oracle.query.createquery = INSERT INTO Queries (user_id, device_id, query_type, status, time_sending, user_message) VALUES (?, ?, ?, 1, SYSDATE, ?)
query.oracle.query.deleteuserqueries = DELETE FROM Queries WHERE user_id = ?
query.oracle.query.closequery = UPDATE Queries SET status = 3, time_closing = SYSDATE, response = ? WHERE query_id = ?
query.oracle.query.getquery = SELECT * FROM Queries JOIN QueryType ON queries.query_type = querytype.type_id JOIN querystatus ON queries.status = querystatus.status_id JOIN UserData ON queries.user_id = UserData.user_id JOIN OfficeDevice ON queries.device_id = OfficeDevice.device_id WHERE query_id = ?
query.oracle.query.deletequerieswithdevice = DELETE FROM Queries WHERE device_id = ?

name.servletcontext.dao.userdata = UserDataDAO
name.servletcontext.dao.officedevice = OfficeDeviceDAO
name.servletcontext.dao.query = QueryDAO
name.servletcontext.user = user
name.servletcontext.role = role
name.servletcontext.userheader = userHeader
name.servletcontext.lastpage = lastPage
